# Generated by Django 3.2.6 on 2022-10-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaunaImformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saunaname', models.CharField(max_length=100)),
                ('FreeText', models.TextField()),
            ],
        ),
    ]
