# Generated by Django 3.2.6 on 2022-10-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_saunaname_saunaimformation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saunaimformation',
            name='fee',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
