# Generated by Django 3.2.6 on 2022-10-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_saunaimformation_rouryu'),
    ]

    operations = [
        migrations.AddField(
            model_name='saunaimformation',
            name='place',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
