# Generated by Django 3.2.6 on 2022-10-27 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_saunaimformation_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='saunaimformation',
            name='author',
            field=models.CharField(default='匿名', max_length=100),
        ),
        migrations.AddField(
            model_name='saunaimformation',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='saunaimformation',
            name='place',
            field=models.CharField(max_length=50),
        ),
    ]
