# Generated by Django 3.2.6 on 2022-10-27 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20221027_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saunaimformation',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='saunaimformation',
            name='fee',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='saunaimformation',
            name='rouryu',
            field=models.BooleanField(choices=[(True, 'あり'), (False, 'なし')]),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
